=== stubbedtoe/dan-portfolio/.astro/collections/portfolio.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "alt": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "Dimensions": {
      "type": "object",
      "properties": {
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        }
      },
      "required": [
        "width",
        "height"
      ]
    },
    "year": {
      "type": "string"
    },
    "medium": {
      "type": "string"
    },
    "active": {
      "type": "boolean"
    },
    "areaOfInterest": {
      "type": "string",
      "enum": [
        "top",
        "centre",
        "bottom"
      ]
    },
    "category": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "order": {
      "type": "number"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "alt",
    "id",
    "image",
    "Dimensions",
    "year",
    "medium",
    "active",
    "areaOfInterest",
    "category",
    "order"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/karen-in-naast-withh-the-view-to-tournaig.json
{
  "title": "Karen in Naast with the view to Tournaig",
  "id": "karen-in-naast-withh-the-view-to-tournaig",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 120,
    "height": 89
  },
  "year": "2025-03-03",
  "alt": "A naked woman lying in abstracted landscape with sea and mountains in the background",
  "image": "/src/images/DSC_0924(1).jpg",
  "active": true,
  "areaOfInterest": "bottom",
  "order": 19,
  "category": [
    "personal"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/seonaid-nimmo.json
{
  "title": "Seonaid Nimmo ",
  "id": "seonaid-nimmo",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 95,
    "height": 114
  },
  "year": "2018-05-15",
  "alt": "Woman in front of a colourful landscape of sea and mountains",
  "image": "/src/images/DSC_0390 - Copy.JPG",
  "active": true,
  "areaOfInterest": "centre",
  "order": 28,
  "category": [
    "personal"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/nude-self-portrait.json
{
  "title": "Nude Self Portrait",
  "id": "nude-self-portrait",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 81,
    "height": 170
  },
  "year": "2022-06-08",
  "alt": "A nude man standing and looking upwards. The light is coming from above.",
  "image": "/src/images/Nude Self-Portrait.jpg",
  "active": true,
  "areaOfInterest": "top",
  "order": 8,
  "category": [
    "personal"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/mums-hands.json
{
  "title": "Mums Hands",
  "id": "mums-hands",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 40,
    "height": 40
  },
  "year": "2018-11-23",
  "alt": "A womans hands in her lap",
  "image": "/src/images/Mums Hands.JPG",
  "active": true,
  "areaOfInterest": "centre",
  "order": 26,
  "category": [
    "personal"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/stewart-macrae-with-mv-kindat.json
{
    "title": "Stewart Macrae with MV Kindat",
    "id": "stewart-macrae-with-mv-kindat",
    "medium": "Acrylic on board",
    "Dimensions": {
      "width": 60,
      "height": 74
    },
    "year": "2019-06-19",
    "alt": "An older man pictured against a marine backdrop with a ship on the horizon ",
    "image": "/src/images/Stewart Macrae with MV Kindat - Acrylic on Board - 60cm x 74cm - 20219.jpg",
    "active": true,
    "areaOfInterest": "centre",
    "category": [
      "commissions"
    ],
    "order": 12
  }

=== stubbedtoe/dan-portfolio/src/content/_portfolio/campanula-in-naast.json
{
  "title": "Campanula in Naast",
  "id": "campanula-in-naast",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 23,
    "height": 30
  },
  "year": "2024-03-02",
  "alt": "A violet campanula flower",
  "image": "/src/images/campanula.jpg",
  "active": true,
  "areaOfInterest": "top",
  "order": 13,
  "category": [
    "flowers"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/mellon-charles-gothic.json
{
  "title": "Mellon Charles Gothic",
  "id": "mellon-charles-gothic",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 60,
    "height": 85
  },
  "year": "2023-02-03",
  "alt": "A man holding a chainsaw standing next to a seated woman holding a gardening fork in brightly coloured clothes in a garden setting",
  "image": "/src/images/DSC_0209.jpg",
  "active": true,
  "areaOfInterest": "centre",
  "order": 20,
  "category": [
    "personal"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/self-portrait-at-firemore.json
{
    "title": "Self Portrait at Firemore",
    "id": "self-portrait-at-firemore",
    "medium": "Acrylic on board",
    "Dimensions": {
      "width": 60,
      "height": 70
    },
    "year": "2023-10-10",
    "alt": "Head and shoulders of a man with his hair tied back. He does not have any clothes on. The background is a dark landscape.",
    "image": "/src/images/Self-Portrait at Firemore- Acrylic on Board - 60cm x 70cm - 2023.jpg",
    "active": true,
    "areaOfInterest": "centre",
    "category": [
      "personal"
    ],
    "order": 9
  }
