=== stubbedtoe/dan-portfolio/.astro/collections/portfolio.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "alt": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "Dimensions": {
      "type": "object",
      "properties": {
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        }
      },
      "required": [
        "width",
        "height"
      ]
    },
    "year": {
      "type": "string"
    },
    "medium": {
      "type": "string"
    },
    "active": {
      "type": "boolean"
    },
    "areaOfInterest": {
      "type": "string",
      "enum": [
        "top",
        "centre",
        "bottom"
      ]
    },
    "category": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "order": {
      "type": "number"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "alt",
    "id",
    "image",
    "Dimensions",
    "year",
    "medium",
    "active",
    "areaOfInterest",
    "category",
    "order"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/clem-and-connie.json
{
  "title": "Clem and Connie",
  "id": "clem-and-connie",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 20,
    "height": 30
  },
  "year": "2023-08-22",
  "alt": "Two toddlers standing on the beach with their back to the viewer looking at the sea",
  "image": "/src/images/DSC_0550.JPG",
  "active": true,
  "areaOfInterest": "centre",
  "order": 27,
  "category": [
    "commissions"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/andrew-seated.json
{
  "title": "Andrew Seated",
  "id": "andrew-seated",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 120,
    "height": 120
  },
  "year": "2023-06-07",
  "alt": "A man seated looking to the side with his head resting in his hand",
  "image": "/src/images/Andrew Seated - Acrylic on Board - 120cm x 120cm - 2023.jpg",
  "active": true,
  "areaOfInterest": "centre",
  "category": [
    "personal"
  ],
  "order": 2
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/fennel-in-naast.json
{
  "title": "Fennel in Naast",
  "id": "fennel-in-naast",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 23,
    "height": 30
  },
  "year": "2024-11-28",
  "alt": "A fennel plant with hills in the background",
  "image": "/src/images/fennel - Copy.jpg",
  "active": true,
  "areaOfInterest": "top",
  "order": 14,
  "category": [
    "flowers"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/fern-in-naast.json
{
  "title": "Fern in Naast",
  "id": "fern-in-naast",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 22,
    "height": 29
  },
  "year": "2025-02-13",
  "alt": "A lit up fern with a fark abstract background",
  "image": "/src/images/Fern-NoBorder1 - Copy.jpg",
  "active": true,
  "areaOfInterest": "top",
  "order": 16,
  "category": [
    "flowers"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/john-tiller.json
{
  "title": "John Tiller with bottle of Barolo wine",
  "id": "john-tiller",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 70,
    "height": 89
  },
  "year": "2019-07-03",
  "alt": "A man seated looking at the viewer holding a bottle of Barola wine with vineyards in the background",
  "image": "/src/images/DSC_1348 (2).JPG",
  "active": true,
  "areaOfInterest": "top",
  "order": 18,
  "category": [
    "commissions"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/river-lily-in-naast.json
{
  "title": "River Lily in Naast",
  "id": "river-lily-in-naast",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 23,
    "height": 30
  },
  "year": "2025-04-04",
  "alt": "A pink River Lily with abstract mountains and trees in the background",
  "image": "/src/images/Pink-NoBorder - Copy.jpg",
  "active": true,
  "areaOfInterest": "centre",
  "order": 18,
  "category": [
    "flowers"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/the-doctor.json
{
  "title": "The Doctor",
  "id": "the-doctor",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 50,
    "height": 65
  },
  "year": "2020-05-03",
  "alt": "A man sitting a table looking at the camera surrounded by newspapers",
  "image": "/src/images/DSC_0676 - Copy.JPG",
  "active": true,
  "areaOfInterest": "centre",
  "order": 22,
  "category": [
    "commissions"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/eleaine.json
{
    "title": "Eleaine",
    "id": "eleaine",
    "medium": "Acrylic on board",
    "Dimensions": {
      "width": 45,
      "height": 65
    },
    "year": "2020-06-09",
    "alt": "A smiling red-haired woman with glasses in a blue NHS nurse's uniform looking straight ahead.",
    "image": "/src/images/Eleaine - Acrylic on Board - 45cm x 65cm - 2020.JPG",
    "active": true,
    "areaOfInterest": "centre",
    "category": [
      "personal"
    ],
    "order": 4
  }
