=== stubbedtoe/dan-portfolio/.astro/collections/portfolio.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "alt": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "Dimensions": {
      "type": "object",
      "properties": {
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        }
      },
      "required": [
        "width",
        "height"
      ]
    },
    "year": {
      "type": "string"
    },
    "medium": {
      "type": "string"
    },
    "active": {
      "type": "boolean"
    },
    "areaOfInterest": {
      "type": "string",
      "enum": [
        "top",
        "centre",
        "bottom"
      ]
    },
    "category": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "order": {
      "type": "number"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "alt",
    "id",
    "image",
    "Dimensions",
    "year",
    "medium",
    "active",
    "areaOfInterest",
    "category",
    "order"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/clementine-murray.json
{
  "title": "Clementine Murray",
  "id": "clementine-murray",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 22,
    "height": 30
  },
  "year": "2018-12-27",
  "alt": "A baby girl with a full head of hair being held in arms",
  "image": "/src/images/DSC_0595.JPG",
  "active": true,
  "areaOfInterest": "top",
  "order": 23,
  "category": [
    "personal"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/gooseneck-loosestrife-in-naast.json
{
  "title": "Gooseneck Loosestrife in Naast",
  "id": "gooseneck-loosestrife-in-naast",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 23,
    "height": 30
  },
  "year": "2025-01-22",
  "alt": "A tall white flowered plant with a fly on the side and abstract green and red background",
  "image": "/src/images/White-NoBorder[1] - Copy.jpg",
  "active": true,
  "areaOfInterest": "top",
  "order": 15,
  "category": [
    "flowers"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/mum-in-the-afternoon-light.json
{
    "title": "Mum in the Afternoon Light",
    "id": "mum-in-the-afternoon-light",
    "medium": "Acrylic on board",
    "Dimensions": {
      "width": 23,
      "height": 30
    },
    "year": "2025-03-07",
    "alt": "Close up of a woman's face. She is looking at something out of frame to the upper right.",
    "image": "/src/images/Mum in the afternoon light - Acrylic on Board -  23cm x 30cm - 2025.jpg",
    "active": true,
    "areaOfInterest": "centre",
    "category": [
      "personal"
    ],
    "order": 7
  }

=== stubbedtoe/dan-portfolio/src/content/_portfolio/alan-with-mason.json
{
  "title": "Alan with Manson",
  "id": "alan-with-mason",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 84,
    "height": 135
  },
  "year": "2018-06-07",
  "alt": "A man with long hair with his hand resting on the black and white do beside him. Both subjects are looking forward.",
  "image": "/src/images/Alan with Manson - Acrylic on Board - 84cm x 135cm - 2018.JPG",
  "active": true,
  "areaOfInterest": "top",
  "order": 3,
  "category": [
    "commissions"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/oliver-and-nicola.json
{
  "title": "Oliver and Nicola",
  "id": "oliver-and-nicola",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 24,
    "height": 25
  },
  "year": "2024-06-28",
  "alt": "A cat sleeping on the face of a young woman",
  "image": "/src/images/DSC06783 4 - Copy.jpg",
  "active": true,
  "areaOfInterest": "centre",
  "order": 27,
  "category": [
    "commissions"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/john-and-lyndsay-todd.json
{
    "title": "John and Lyndsay Todd",
    "id": "john-and-lyndsay-todd",
    "medium": "Acrylic on board",
    "Dimensions": {
      "width": 91,
      "height": 120
    },
    "year": "2021-06-09",
    "alt": "A man and a woman embracing. The man has a tattoo on his arm and the woman is heavily pregnant.",
    "image": "/src/images/John and Lyndsay Todd - Acrylic on Board - 91cm x  120cm - 2021.jpg",
    "active": true,
    "areaOfInterest": "centre",
    "category": [
      "personal"
    ],
    "order": 5
  }

=== stubbedtoe/dan-portfolio/src/content/_portfolio/isobel-armstrong-in-front-of-ardmore.json
{
  "title": "Isobel Armstrong in front of Ardmore",
  "id": "isobel-armstrong-in-front-of-ardmore",
  "medium": "Acrylic on board",
  "Dimensions": {
    "width": 60,
    "height": 74
  },
  "year": "2024-09-22",
  "alt": "Elderly woman smiling in front of her home",
  "image": "/src/images/Isobel Armstron.jpg",
  "active": true,
  "areaOfInterest": "centre",
  "order": 28,
  "category": [
    "commissions"
  ]
}

=== stubbedtoe/dan-portfolio/src/content/_portfolio/sandy-macrae.json
{
    "title": "Sandy Macrae",
    "id": "sandy-macrae",
    "medium": "Acrylic on canvas",
    "Dimensions": {
      "width": 42,
      "height": 60
    },
    "year": "2019-06-05",
    "alt": "A hooded middle-aged man staring straight ahead",
    "image": "/src/images/Sandy Macrae - Acrylic on Canvas - 42cm x 60cm - 2019.jpg",
    "active": true,
    "areaOfInterest": "centre",
    "category": [
      "commissions"
    ],
    "order": 10
  }
